openapi: 3.0.0
info:
  title: Chariot Specification
  version: 0.0.1-$REVISION
  description: Chariot server for goseidon
  contact:
    name: Support
    url: 'https://github.com/go-seidon/'
    email: raka.suryaardi@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3030/'
    description: local
paths:
  /:
    get:
      operationId: GetAppInfo
      summary: get app info
      description: get app info
      tags:
        - app
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
      responses:
        '200':
          description: success get app info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAppInfoResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success
                    data:
                      app_name: chariot
                      app_version: 1.0.0
      security:
        - basicAuth: []
  /file:
    post:
      operationId: UploadFile
      summary: upload file
      description: upload file
      tags:
        - file
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
      requestBody:
        description: file to be uploaded
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadFileRequest'
      responses:
        '200':
          description: success upload file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFileResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success upload file
                    data:
                      file_id: 2FfnA2ifBQDT5bMFRCvcdnIhVmg
                      file_url: 'http://localhost:3030/file/lumba-lumba.jpg'
                      uploaded_at: 1664891858856
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
  '/file/{slug}':
    get:
      operationId: RetrieveFileBySlug
      summary: retrieve file object
      description: retrieve file object
      tags:
        - file
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/ObjectSlug'
      responses:
        '200':
          description: success retrieve file
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/RetrieveFileBySlugResponse'
          headers:
            X-File-Name:
              schema:
                type: string
                description: file name
                example: dolphin
            X-File-Extension:
              schema:
                type: string
                description: file extension
                example: jpg
            X-File-Mimetype:
              schema:
                type: string
                description: file mimetype
                example: image/jpeg
            X-File-Size:
              schema:
                type: integer
                format: int64
                description: file size
                example: 18934
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/ForbiddenAccess'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
  /v1/barrel:
    post:
      operationId: CreateBarrel
      summary: create barrel
      description: create barrel
      tags:
        - barrel
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
      requestBody:
        description: barrel information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBarrelRequest'
      responses:
        '201':
          description: success create barrel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBarrelResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success
                    data:
                      id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                      code: hippo-1
                      name: Hippo 1
                      provider: goseidon_hippo
                      status: inactive
                      created_at: 1664803257299
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
  /v1/barrel/search:
    post:
      operationId: SearchBarrel
      summary: search barrel
      description: search barrel
      tags:
        - barrel
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
      requestBody:
        description: search parameter
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchBarrelRequest'
            examples:
              All Parameter:
                value:
                  keyword: hip
                  pagination:
                    total_items: 25
                    page: 1
                  filter:
                    status_in:
                      - active
                      - inactive
                    provider_in:
                      - goseidon_hippo
                      - aws_s3
                      - gcloud_stroage
                      - alicloud_oss
              Keyword:
                value:
                  keyword: hip
              Pagination:
                value:
                  pagination:
                    total_items: 25
                    page: 1
              Some Filter:
                value:
                  filter:
                    status_in:
                      - active
              All Filter:
                value:
                  filter:
                    status_in:
                      - active
                      - inactive
                    provider_in:
                      - goseidon_hippo
                      - aws_s3
                      - gcloud_stroage
                      - alicloud_oss
      responses:
        '200':
          description: success search barrel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchBarrelResponse'
              examples:
                Empty Result:
                  value:
                    code: 1000
                    message: success
                    data: []
                Some Result:
                  value:
                    code: 1000
                    message: success
                    data:
                      - id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                        code: hippo-1
                        name: Hippo 1
                        provider: goseidon_hippo
                        status: inactive
                        created_at: 1664803257299
                Max Result:
                  value:
                    code: 1000
                    message: success
                    data:
                      - id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                        code: hippo-1
                        name: Hippo 1
                        provider: goseidon_hippo
                        status: inactive
                        created_at: 1664803257299
                      - id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                        code: hippo-2
                        name: Hippo 2
                        provider: goseidon_hippo
                        status: active
                        created_at: 1664803257299
                        updated_at: 1664803257300
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
  '/v1/barrel/{id}':
    put:
      operationId: UpdateBarrelById
      summary: update barrel
      description: update barrel
      tags:
        - barrel
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/ObjectId'
      requestBody:
        description: barrel information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBarrelByIdRequest'
      responses:
        '200':
          description: success update barrel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateBarrelByIdResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success
                    data:
                      id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                      code: hippo-1
                      name: Hippo 1
                      provider: goseidon_hippo
                      status: inactive
                      created_at: 1664803257299
                      updated_at: 1664803257300
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
    get:
      operationId: GetBarrelById
      summary: get barrel
      description: get barrel
      tags:
        - barrel
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/ObjectId'
      responses:
        '200':
          description: success get barrel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBarrelByIdResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success
                    data:
                      id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                      code: hippo-1
                      name: Hippo 1
                      provider: goseidon_hippo
                      status: inactive
                      created_at: 1664803257299
                      updated_at: 1664803257300
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
  /v1/auth-client:
    post:
      operationId: CreateAuthClient
      summary: create auth client
      description: create auth client
      tags:
        - auth-client
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
      requestBody:
        description: auth client information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthClientRequest'
      responses:
        '201':
          description: success create auth client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAuthClientResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success
                    data:
                      id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                      name: Service A
                      status: inactive
                      type: basic_auth
                      client_id: goseidon
                      created_at: 1664803257299
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
  /v1/auth-client/search:
    post:
      operationId: SearchAuthClient
      summary: search auth client
      description: search auth client
      tags:
        - auth-client
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
      requestBody:
        description: search parameter
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchAuthClientRequest'
            examples:
              All Parameter:
                value:
                  keyword: ser
                  pagination:
                    total_items: 25
                    page: 1
                  filter:
                    status_in:
                      - active
                      - inactive
              Keyword:
                value:
                  keyword: ser
              Pagination:
                value:
                  pagination:
                    total_items: 25
                    page: 1
              All Filter:
                value:
                  filter:
                    status_in:
                      - active
                      - inactive
      responses:
        '200':
          description: success search auth client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchAuthClientResponse'
              examples:
                Empty Result:
                  value:
                    code: 1000
                    message: success
                    data: []
                Some Result:
                  value:
                    code: 1000
                    message: success
                    data:
                      - id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                        name: Service A
                        status: inactive
                        type: basic_auth
                        client_id: goseidon
                        created_at: 1664803257299
                        updated_at: 1664803257300
                Max Result:
                  value:
                    code: 1000
                    message: success
                    data:
                      - id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                        name: Service A
                        status: inactive
                        type: basic_auth
                        client_id: goseidon
                        created_at: 1664803257299
                        updated_at: 1664803257300
                      - id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                        name: Service A
                        status: active
                        type: basic_auth
                        client_id: goseidon
                        created_at: 1664803257299
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
  '/v1/auth-client/{id}':
    put:
      operationId: UpdateAuthClientById
      summary: update auth client
      description: update auth client
      tags:
        - auth-client
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/ObjectId'
      requestBody:
        description: auth client information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthClientByIdRequest'
      responses:
        '200':
          description: success update auth client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAuthClientByIdResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success
                    data:
                      id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                      name: Service A
                      status: inactive
                      type: basic_auth
                      client_id: goseidon
                      created_at: 1664803257299
                      updated_at: 1664803257300
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
    get:
      operationId: GetAuthClientById
      summary: get auth client
      description: get auth client
      tags:
        - auth-client
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/ObjectId'
      responses:
        '200':
          description: success get auth client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAuthClientByIdResponse'
              examples:
                Success:
                  value:
                    code: 1000
                    message: success
                    data:
                      id: 2EvNFKm97MjLU0JNSOYnoyMFv9i
                      name: Service A
                      status: inactive
                      type: basic_auth
                      client_id: goseidon
                      created_at: 1664803257299
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthenticatedAccess'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
      security:
        - basicAuth: []
components:
  parameters:
    ObjectId:
      name: id
      in: path
      required: true
      description: object id
      schema:
        type: string
    ObjectSlug:
      name: slug
      in: path
      required: true
      description: object slug
      schema:
        type: string
    CorrelationId:
      name: X-Correlation-Id
      in: header
      required: false
      description: correlation id for tracing purposes
      schema:
        type: string
  schemas:
    ResponseBodyInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    RequestPagination:
      type: object
      required:
        - total_items
        - page
      properties:
        total_items:
          type: integer
          description: 'min = 1, max = 200'
        page:
          type: integer
          format: int64
          description: min = 1
    GetAppInfoResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/GetAppInfoData'
    GetAppInfoData:
      type: object
      required:
        - app_name
        - app_version
      properties:
        app_name:
          type: string
        app_version:
          type: string
    CreateBarrelRequest:
      type: object
      required:
        - code
        - name
        - provider
        - status
      properties:
        code:
          type: string
        name:
          type: string
        provider:
          type: string
        status:
          type: string
    CreateBarrelResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/CreateBarrelData'
    CreateBarrelData:
      type: object
      required:
        - id
        - code
        - name
        - provider
        - status
        - created_at
      properties:
        id:
          type: string
        code:
          type: string
        name:
          type: string
        provider:
          type: string
        status:
          type: string
        created_at:
          type: integer
          format: int64
    UpdateBarrelByIdRequest:
      type: object
      required:
        - code
        - name
        - provider
        - status
      properties:
        code:
          type: string
        name:
          type: string
        provider:
          type: string
        status:
          type: string
    UpdateBarrelByIdResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/UpdateBarrelByIdData'
    UpdateBarrelByIdData:
      type: object
      required:
        - id
        - code
        - name
        - provider
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
        code:
          type: string
        name:
          type: string
        provider:
          type: string
        status:
          type: string
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
    GetBarrelByIdResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/GetBarrelByIdData'
    GetBarrelByIdData:
      type: object
      required:
        - id
        - code
        - name
        - provider
        - status
        - created_at
      properties:
        id:
          type: string
        code:
          type: string
        name:
          type: string
        provider:
          type: string
        status:
          type: string
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
    SearchBarrelRequest:
      type: object
      properties:
        keyword:
          type: string
          description: min = 2 character
        pagination:
          $ref: '#/components/schemas/RequestPagination'
        filter:
          $ref: '#/components/schemas/SearchBarrelFilter'
    SearchBarrelFilter:
      type: object
      properties:
        status_in:
          type: array
          items:
            type: string
            enum:
              - active
              - inactive
            description: barrel status
        provider_in:
          type: array
          items:
            type: string
            enum:
              - goseidon_hippo
              - aws_s3
              - gcloud_stroage
              - alicloud_oss
            description: barrel provider
    SearchBarrelResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/SearchBarrelItem'
    SearchBarrelItem:
      type: object
      required:
        - id
        - code
        - name
        - provider
        - status
        - created_at
      properties:
        id:
          type: string
        code:
          type: string
        name:
          type: string
        provider:
          type: string
        status:
          type: string
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
    CreateAuthClientRequest:
      type: object
      required:
        - name
        - status
        - type
      properties:
        name:
          type: string
        status:
          type: string
          enum:
            - active
            - inactive
        type:
          type: string
          enum:
            - basic_auth
        client_id:
          type: string
        client_secret:
          type: string
    CreateAuthClientResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/CreateAuthClientData'
    CreateAuthClientData:
      type: object
      required:
        - id
        - name
        - status
        - type
        - created_at
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
        type:
          type: string
        client_id:
          type: string
        created_at:
          type: integer
          format: int64
    UpdateAuthClientByIdRequest:
      type: object
      required:
        - name
        - status
        - type
      properties:
        name:
          type: string
        status:
          type: string
          enum:
            - active
            - inactive
        type:
          type: string
          enum:
            - basic_auth
        client_id:
          type: string
        client_secret:
          type: string
    UpdateAuthClientByIdResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/UpdateAuthClientByIdData'
    UpdateAuthClientByIdData:
      type: object
      required:
        - id
        - name
        - status
        - type
        - created_at
        - updated_at
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
        type:
          type: string
        client_id:
          type: string
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
    GetAuthClientByIdResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/GetAuthClientByIdData'
    GetAuthClientByIdData:
      type: object
      required:
        - id
        - name
        - status
        - type
        - created_at
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
        type:
          type: string
        client_id:
          type: string
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
    SearchAuthClientRequest:
      type: object
      properties:
        keyword:
          type: string
          description: min = 2 character
        pagination:
          $ref: '#/components/schemas/RequestPagination'
        filter:
          $ref: '#/components/schemas/SearchAuthClientFilter'
    SearchAuthClientFilter:
      type: object
      properties:
        status_in:
          type: array
          items:
            type: string
            enum:
              - active
              - inactive
            description: auth client status
    SearchAuthClientResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/SearchAuthClientItem'
    SearchAuthClientItem:
      type: object
      required:
        - id
        - name
        - status
        - type
        - created_at
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
        type:
          type: string
        client_id:
          type: string
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
    UploadFileRequest:
      type: object
      required:
        - file
        - visibility
        - barrels
      properties:
        file:
          type: string
          format: binary
        visibility:
          type: string
          enum:
            - public
            - protected
        barrels:
          type: string
          description: csv of barrel code
        rule:
          type: string
          description: rule code
        metadata:
          type: string
          description: json metadata
    UploadFileResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/UploadFileData'
    UploadFileData:
      type: object
      required:
        - file_id
        - uploaded_at
      properties:
        file_id:
          type: string
        file_url:
          type: string
        uploaded_at:
          type: integer
          format: int64
    RetrieveFileBySlugResponse:
      type: string
      format: binary
  responses:
    BadRequest:
      description: invalid parameter
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseBodyInfo'
          examples:
            Bad Request:
              value:
                code: 1002
                message: property must be at least 5 characters in length
    UnauthenticatedAccess:
      description: unauthenticated access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseBodyInfo'
          examples:
            Invalid Credential:
              value:
                code: 1003
                message: credential is invalid
    ForbiddenAccess:
      description: forbidden access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseBodyInfo'
          examples:
            Forbidden Access:
              value:
                code: 1003
                message: forbiden access
    NotFound:
      description: resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseBodyInfo'
          examples:
            Not Found:
              value:
                code: 1004
                message: not found
    ServerError:
      description: failed do action
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseBodyInfo'
          examples:
            General Error:
              value:
                code: 1001
                message: network error
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

